FROM node:9

#ARG NODE_ENV=production
#ENV NODE_ENV=$NODE_ENV

WORKDIR /usr/src/react/

# Install Node.js dependencies
# COPY package.json yarn.lock ./
# RUN npm install --production

EXPOSE 3000
CMD ["yarn", "run", "start"]
