FROM node:9

#ARG NODE_ENV=production
#ENV NODE_ENV=$NODE_ENV

WORKDIR /usr/src/react/

# Install Node.js dependencies
#COPY package.json yarn.lock ./
#RUN set -ex; \
#  if [ "$NODE_ENV" = "production" ]; then \
#    yarn install --no-cache --frozen-lockfile --production; \
#  elif [ "$NODE_ENV" = "test" ]; then \
#    yarn install --no-cache --frozen-lockfile; \
#  fi;

EXPOSE 3000
CMD ["yarn", "run", "start"]
