module.exports = {
  CLIENT_STATUS: {
    NONE: -1,
    REQUESTING: 1,
    REQUESTING_SERVICE_INFO: 10,
    REQUESTING_STOP_TRAINING: 11,
    REQUESTING_FILES: 12,
    REQUESTING_PREDICT: 13,
    REQUESTING_TRAINING: 14
  },

  SERVER_STATUS: {
    NONE: -1,
    ERROR: 1,
    PREDICT: 2,
    TRAINING: 3,
    TRAINING_STOPPED: 31,
    TRAINING_RUNNING: 32,
    TRAINING_FINISHED: 33
  }
};
