FROM nginx

ADD /config/nginx/nginx.eris.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/www/html
COPY ./public/favicon.ico /var/www/html
COPY ./public/manifest.json /var/www/html

RUN mkdir /var/www/html/css
COPY ./public/css /var/www/html/css

RUN mkdir /var/www/html/webfonts
COPY ./public/webfonts /var/www/html/webfonts

EXPOSE 80
